version: "3.8"

services:
  web:
    container_name: cursoreact
    build: .
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - .:/code
    networks:
      - edu-shared
    command: sh -c "npm install && npm run dev"

networks:
  edu-shared:
    external: true